server:
  port: 8083
  servlet:
    context-path: /dev

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.erp.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
    datasource:
               # 订单数据源配置信息
                userdatasource:
                    name: test
                    url: jdbc:mysql://127.0.0.1:3306/mytest?useSSL=false&useUnicode=true&serverTimezone=UTC
                    username: root
                    password: 123456
                    # 使用druid数据源
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    filters: stat
                    maxActive: 20
                    initialSize: 1
                    maxWait: 60000
                    minIdle: 1
                    timeBetweenEvictionRunsMillis: 60000
                    minEvictableIdleTimeMillis: 300000
                    validationQuery: select 'x'
                    testWhileIdle: true
                    testOnBorrow: false
                    testOnReturn: false
                    poolPreparedStatements: true
                    maxOpenPreparedStatements: 20

redis:
    shiro:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:      # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
          pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
