spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        min-idle: 0
    password: 123456
    block-when-exhausted: true  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true


  freemarker:
    suffix: .html
    request-context-attribute: request


lbplatform:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: true # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
